---
- hosts: localhost
  strategy: debug
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
  - name: Update and upgrade apt packages
    apt:
      force_apt_get: yes
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: install tzdata
    apt:
      name: tzdata
      state: present

  - name: set timezone
    shell: |
      export DEBIAN_FRONTEND=noninteractive
      ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
      dpkg-reconfigure --frontend noninteractive tzdata