apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev gdebi-core libmariadbclient-dev libsodium-dev
#libmariadb-client-lgpl-dev
R -e "install.packages(c('purrr'))"
R -e "install.packages(c('plyr'))"
R -e "install.packages(c('dplyr'))"
R -e "install.packages(c('pool'))"
R -e "install.packages(c('DBI'))"
R -e "install.packages(c('shiny'))"
R -e "install.packages(c('RMySQL'))"
R -e "install.packages(c('shinydashboard'))"
R -e "install.packages(c('rvest'))"
R -e "install.packages(c('tidyverse'))"
R -e "install.packages(c('tidyr'))"
R -e "install.packages(c('stringr'))"
R -e "install.packages(c('shinyjs'))"
R -e "install.packages(c('shinycssloaders'))"
R -e "install.packages(c('shinyjs'))"
R -e "install.packages(c('v8'))"
R -e "install.packages(c('DT'))"
R -e "install.packages(c('proto'))"
R -e "install.packages(c('rPython'))"
R -e "install.packages(c('RMySQL'))"
R -e "install.packages(c('lubridate'))"
R -e "install.packages(c('gsubfn'))"
R -e "install.packages(c('highcharter'))"
R -e "install.packages(c('sodium'))"
